#!/usr/bin/env python3

from argparse import ArgumentParser
from dataclasses import dataclass, field
from pathlib import Path
import json
import os
import secrets
import shlex
import shutil
import subprocess as sp
import sys
import typing as tp

#   Python's build-in hash() function is used to tag file data for comparison
#   purposes unless the xxhash package is available. In that case, a 128-bit
#   hash is used, hopefully resulting in fewer unwanted collisions.
try:
    import xxhash
    g_got_xxhash = True

    #   A random 128-bit seed value for the xxh128 algorithm. As of Python 3.3,
    #   the built-in hash() is salted -- presumably to prevent some sort of
    #   DDoS attack -- so might as well do the same with xxhash.
    g_seed = secrets.token_bytes(16)

except ImportError:
    g_got_xxhash = False


# ---- Config Management ------------------------------------------------------


k_config_path: tp.Final[Path] = \
    Path.home()/"Library"/"Preferences"/"apfs_archive.json"


@dataclass
class Config:
    blk_size: int = 0x100000  # default = 1 MB
    clone_files: bool = True
    delete_orig: bool = False
    dmg_format: str = "ULMO"  # LZMA-compressed (10.15 Catalina or later)

    def save(self):
        json_obj = {
            "blk_size": self.blk_size,
            "clone_files": self.clone_files,
            "delete_orig": self.delete_orig,
            "dmg_format": self.dmg_format
        }
        with open(k_config_path, "w") as outf:
            json.dump(json_obj, outf, indent="\t")

    def display(self, outf: tp.TextIO):
        print("blk_size:", self.blk_size, file=outf)
        print("clone_files:", self.clone_files, file=outf)
        print("delete_orig:", self.delete_orig, file=outf)
        print("dmg_format:", self.dmg_format, file=outf)
        if g_got_xxhash:
            print("xxhash will be used", file=outf)


def load_config() -> Config:
    if k_config_path.is_file():
        with open(k_config_path) as inf:
            json_obj = json.load(inf)
        return config_from_json(json_obj=json_obj, default=Config())
    return Config()


def config_from_json(json_obj: dict[str, tp.Any], default: Config) -> Config:
    return Config(
        blk_size=json_obj.get("blk_size", default.blk_size),
        clone_files=json_obj.get("clone_files", default.clone_files),
        delete_orig=json_obj.get("delete_orig", default.delete_orig),
        dmg_format=json_obj.get("dmg_format", default.dmg_format)
    )


# -----------------------------------------------------------------------------


@dataclass(frozen=True)
class DataSig:
    """
    This is the key type used by the `scanned` dictionary that hopefully
    uniquely identifies file contents.

    Attributes:
        size: size of the file data in bytes
        hash_val: a hash of the file data
            This may be generated by the built-in hash() function (the int
            case) or by an xxhash algorithm (the bytes digest case).
    """
    size: int
    hash_val: tp.Union[int, bytes]


@dataclass
class CloneSavings:
    before: int = 0
    after: int = 0


@dataclass
class APFSArchive:
    """
    If you import this module from another Python script, you can use an
    instance of APFSArchive and call its run() method to get the same
    functionality as the command line.

    Attributes:
        config:
            This is either read from the Preferences or default-initialized.
        dst_dir:
            If left unassigned, the get_dst_dir() method will return the parent
            directory of the src_dir you pass it instead.
        estimate:
            Estimate mode simply scans the source folder in an attempt to
            determine how much storage could be saved just by cloning
            duplicate files alone. No dmg is created in this case.

            WARNING: xxhash is required for this option.
        outf:
            All program output should be directed here. It defaults to stdout,
            but you could send it to a log file, for example.
    """
    config: Config = field(default_factory=load_config)
    dst_dir: tp.Optional[Path] = None
    estimate: bool = False
    outf: tp.TextIO = sys.stdout

    def run(self, src_dir: Path) -> Path:
        if not src_dir.is_dir():
            raise ValueError(f"{quoted_path(src_dir)} is not a directory")
        src_stat = src_dir.stat()

        if self.estimate:
            savings = self.estimate_clone_savings(src_dir)
            pcnt = savings.after / savings.before * 100.0
            print(
                "estimated total file data storage:",
                savings.before, file=self.outf
            )
            print(
                "estimated storage after eliminating duplicates:",
                savings.after, f"({pcnt:.2f}% of original)",
                file=self.outf
            )
            return src_dir

        if not self.config.clone_files:
            dmg_path = self.get_dst_dir(src_dir)/f"{src_dir.name}.dmg"
            print(
                "making", quoted_path(dmg_path),
                "from", quoted_path(src_dir), file=self.outf
            )
            cmd = [
                "hdiutil", "create",
                "-srcfolder", str(src_dir),
                "-fs", "APFS",
                "-format", self.config.dmg_format,
                "-volname", src_dir.name,
                str(dmg_path)
            ]
            sp.run(
                cmd, check=True, stdout=self.outf, stderr=sp.STDOUT, text=True
            )
            return dmg_path

        tmp_dmg = self.get_dst_dir(src_dir)/f"{src_dir.name}_tmp.dmg"
        print(
            "making temporary", quoted_path(tmp_dmg),
            "from", quoted_path(src_dir), file=self.outf
        )
        cmd = [
            "hdiutil", "create",
            "-srcfolder", str(src_dir),
            "-fs", "APFS",
            "-format", "UDRW",
            "-volname", src_dir.name,
            str(tmp_dmg)
        ]
        sp.run(cmd, check=True, stdout=self.outf, stderr=sp.STDOUT, text=True)
        try:
            final_dmg = self._handle_tmp_dmg(src_dir, tmp_dmg)
        finally:
            print("deleting", quoted_path(tmp_dmg), file=self.outf)
            tmp_dmg.unlink()
        print(
            "setting", quoted_path(final_dmg),
            "times to match", quoted_path(src_dir), file=self.outf
        )
        os.utime(final_dmg, ns=(src_stat.st_atime_ns, src_stat.st_mtime_ns))
        if self.config.delete_orig:
            print("deleting", quoted_path(src_dir), file=self.outf)
            shutil.rmtree(str(src_dir))
        return final_dmg

    def get_dst_dir(self, src_dir: Path) -> Path:
        return self.dst_dir or src_dir.parent

    def scan_file_data(self, path: Path) -> DataSig:
        """
        Reads the file data and generates a hash as it goes.
        """
        size = 0
        with open(path, "rb") as inf:
            if g_got_xxhash:

                #   With xxhash, it is easy to start from the seed and update
                #   it with file data as we go.
                xxh = xxhash.xxh128(g_seed)
                buf = inf.read(self.config.blk_size)
                while buf:
                    size += len(buf)
                    xxh.update(buf)
                    buf = inf.read(self.config.blk_size)
                return DataSig(size=size, hash_val=xxh.digest())

            #   With the built-in hash, I am not aware of any way to build it
            #   up in piecemeal fashion. So we hash each block, and then make
            #   a hash from the hashes.
            hashes: list[int] = []
            buf = inf.read(self.config.blk_size)
            while buf:
                size += len(buf)
                hashes.append(hash(buf))
                buf = inf.read(self.config.blk_size)

        return DataSig(
            size=size,
            hash_val=hashes[0] if len(hashes) == 1 else hash(tuple(hashes))
        )

    def file_data_matches(self, path1: Path, path2: Path) -> bool:
        with open(path1, "rb") as inf1:
            with open(path2, "rb") as inf2:
                buf1 = inf1.read(self.config.blk_size)
                buf2 = inf2.read(self.config.blk_size)
                while buf1:
                    if buf1 != buf2:
                        return False
                    buf1 = inf1.read(self.config.blk_size)
                    buf2 = inf2.read(self.config.blk_size)
        return buf1 == buf2

    def clone_file(self, target: Path, with_file: Path):
        target.unlink()
        cmd = ["ditto", "--clone", str(with_file), str(target)]
        sp.run(cmd, check=True, stdout=self.outf, stderr=sp.STDOUT, text=True)

    def estimate_clone_savings(self, dir_path: Path) -> CloneSavings:
        if not g_got_xxhash:
            print("please install: python3 -m pip xxhash", file=self.outf)
            raise NotImplementedError(
                "estimating clone savings requires xxhash package"
            )
        print(
            "scanning", quoted_path(dir_path),
            "for possible duplicate files", file=self.outf
        )
        scanned: set[DataSig] = set()
        savings = CloneSavings()
        for base_dir, dir_names, file_names in os.walk(dir_path):
            for file_name in file_names:
                file_path = Path(base_dir, file_name)
                if not file_path.is_file() or file_path.is_symlink():
                    continue
                data_sig = self.scan_file_data(path=file_path)
                if data_sig.size == 0:
                    continue

                #   The actual storage footprint of a file is harder to
                #   determine than you might think? It should be related to the
                #   number of blocks it occupies on disk, but a sparse file may
                #   have unallocated blocks somewhere in the middle. It is not
                #   clear to me whether imaging a folder preserves these holes
                #   or not? So the storage is taken to be the higher number
                #   between the block count and the actual file size, rounded
                #   up to the nearest 4096 byte multiple (the size of APFS
                #   allocation blocks). This should probably be revisited at
                #   some point.
                storage = max(data_sig.size, file_path.stat().st_blocks * 512)
                storage = (storage + 4095) & ~4095

                savings.before += storage
                if data_sig in scanned:
                    #   To be rigorous about it, we would want to check that
                    #   this is truly a duplicate file by comparing contents
                    #   and not just hoping the hashes are unique. This is
                    #   done for real by _handle_tmp_dmg_scan() when dmgs are
                    #   involved. But since this is only an estimate, we assume
                    #   xxhash's 128-bit value is sufficient to ensure
                    #   uniqueness.
                    print(
                        "file", quoted_path(file_path),
                        "is likely a duplicate",
                        f"(estimated {storage} bytes of storage)",
                        file=self.outf
                    )
                else:
                    scanned.add(data_sig)
                    savings.after += storage
        return savings

    def _handle_tmp_dmg(self, src_dir: Path, tmp_dmg: Path) -> Path:
        print("temporarily mounting", quoted_path(tmp_dmg), file=self.outf)
        cmd = ["hdiutil", "attach", str(tmp_dmg)]
        res = sp.run(
            cmd, check=True, stdout=sp.PIPE, stderr=self.outf, text=True
        )
        device = ""
        volume = ""
        for line in res.stdout.splitlines():
            if not device and line.strip().startswith("/dev/"):
                device = line.split()[0]
            i = line.find("/Volumes")
            if i >= 0:
                volume = line[i:].strip()
        if not device or not volume:
            raise ValueError("unexpected output from `hdituil attach`")
        try:
            self._handle_tmp_dmg_scan(Path(volume))
        finally:
            print("unmounting", quoted_path(tmp_dmg), file=self.outf)
            cmd = ["hdiutil", "detach", device]
            sp.run(
                cmd, check=True, stdout=sp.PIPE, stderr=self.outf, text=True
            )

        final_dmg = self.get_dst_dir(src_dir)/f"{src_dir.name}.dmg"
        if final_dmg.exists():
            print("deleting old", quoted_path(final_dmg), file=self.outf)
            final_dmg.unlink()
        print(
            "creating final compressed", quoted_path(final_dmg),
            "from", tmp_dmg, file=self.outf
        )
        cmd = [
            "hdiutil", "convert", str(tmp_dmg),
            "-format", self.config.dmg_format,
            "-o", str(final_dmg)
        ]
        sp.run(cmd, check=True, stdout=sp.PIPE, stderr=self.outf, text=True)
        return final_dmg

    def _handle_tmp_dmg_scan(self, volume_path):
        print("scanning for duplicate files", file=self.outf)
        scanned: dict[DataSig, list[Path]] = {}
        for base_dir, dir_names, file_names in os.walk(volume_path):
            for file_name in file_names:
                file_path = Path(base_dir, file_name)
                if not file_path.is_file() or file_path.is_symlink():
                    continue
                data_sig = self.scan_file_data(path=file_path)
                if data_sig.size == 0:
                    continue
                try:
                    matching_files = scanned[data_sig]
                    for candidate in matching_files:
                        if self.file_data_matches(file_path, candidate):
                            print(
                                "cloning", quoted_path(file_path),
                                "from", quoted_path(candidate), file=self.outf
                            )
                            self.clone_file(file_path, candidate)
                            break
                    else:
                        matching_files.append(file_path)
                except KeyError:
                    scanned[data_sig] = [file_path]


def quoted_path(path: Path) -> str:
    return shlex.quote(str(path))


def command_line_run():
    ap = ArgumentParser(
        description="""
            This script creates a compressed disk image (.dmg) from a
            directory. The internal format within the image is APFS, and before
            the final image is created, any duplicate files are cloned to
            reduce storage size.
            """
    )
    ap.add_argument(
        "src_dirs", metavar="SRC_DIR", nargs="*",
        help="One or more directory paths to archive."
    )
    ap.add_argument(
        "-d", "--dst-dir", default="",
        help="""
            Destination directory for .dmg file.
            If not supplied, they will go in the parent of each source
            directory."""
    )
    ap.add_argument(
        "-e", "--estimate", action="store_true",
        help="""
            In estimate mode, no dmg is created. Rather, the source directory
            is scanned to estimate how much space may be saved just from
            cloning duplicate files alone. Note that the final compression
            phase of the dmg would likely affect how much space is actually
            saved. The output is mainly to check whether it is worth disabling
            clone_files when creating the dmg. NB: This option requires the
            xxhash package. Install with: python3 -m pip install xxhash
            """
    )
    ap.add_argument(
        "-C", "--config-file", default="",
        help=f"""
            Use a json config file to set run parameters. These will also be
            saved to {quoted_path(k_config_path)} to use as future defaults.
            """
    )
    ap.add_argument(
        "-c", "--config", action="append",
        help="""
            This option allows you to override a single configuration parameter
            such as -c 'dmg_format:"UDRO"' (to create an uncompressed dmg when
            you know your data are already compressed). You may specify more
            than one -c option to override multiple parameters. Unlike -C,
            these options do not overwrite the defaults.
            """
    )
    res = ap.parse_args()
    dst_dir = Path(res.dst_dir) if res.dst_dir else None
    try:
        if res.config_file:
            with open(res.config_file) as inf:
                json_obj = json.load(inf)
            config_from_json(json_obj, Config()).save()
        arc = APFSArchive(dst_dir=dst_dir)
        if res.config:
            json_parts: list[str] = ["{"]
            for cfg in res.config:
                k, v = cfg.split(":", maxsplit=1)
                json_parts.append(f'''"{k.strip().strip('"')}"''')
                json_parts.append(f": {v}")
            json_parts.append("}")
            json_obj = json.loads("".join(json_parts))
            arc.config = config_from_json(json_obj, arc.config)
        arc.estimate = res.estimate
        arc.config.display(outf=sys.stdout)
        print("estimate mode:", arc.estimate)
        if res.src_dirs:
            err: tp.Optional[Exception] = None
            for src_dir in map(Path, res.src_dirs):
                try:
                    arc.run(src_dir=src_dir)
                except Exception as err0:
                    err = err or err0
            if err:
                raise err
        else:
            print("no directories specified", file=arc.outf)
        print("complete", file=arc.outf)
    except Exception as err:
        print("ERROR:", err, file=sys.stderr)
        sys.exit(1)


def automator_run():
    log_path = Path.home()/"Library"/"Logs"/"apfs_archive.log"
    with open(log_path, "w") as outf:
        cmd = ["open", "-a", "Console", str(log_path)]
        sp.run(cmd, stdout=outf, stderr=sp.STDOUT, text=True)
        arc = APFSArchive(outf=outf)
        arc.config.display(outf=sys.stdout)
        err: tp.Optional[Exception] = None
        for src_dir in map(Path, sys.argv[1:]):
            try:
                arc.run(src_dir=src_dir)
            except Exception as err0:
                err = err or err0
        if err:
            raise err
        print("complete", file=outf)


if __name__ == "__main__":
    command_line_run()
